import { User, AttendanceRecord, LeaveRequest, NotificationItem, AttendanceStatus } from '../types/hrms';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr_admin_1',
    employeeId: 'EMP-001',
    name: 'Sarah Jenkins',
    email: 'sarah.jenkins@dayflow.hr',
    role: 'ADMIN',
    department: 'Human Resources',
    jobTitle: 'Head of HR Operations',
    joinDate: '2022-01-15',
    phone: '+1 (555) 234-5678',
    address: '742 Evergreen Terrace, San Francisco, CA',
    photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    salary: {
      basic: 6000,
      hra: 2400,
      allowances: 1600,
      deductions: 1200,
      netPay: 8800,
    },
  },
  {
    id: 'usr_emp_1',
    employeeId: 'EMP-102',
    name: 'Alex Morgan',
    email: 'alex.morgan@dayflow.hr',
    role: 'EMPLOYEE',
    department: 'Engineering',
    jobTitle: 'Senior Frontend Developer',
    joinDate: '2023-03-10',
    phone: '+1 (555) 876-5432',
    address: '124 Conch Street, Austin, TX',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    salary: {
      basic: 5200,
      hra: 2000,
      allowances: 1300,
      deductions: 1000,
      netPay: 7500,
    },
  },
  {
    id: 'usr_emp_2',
    employeeId: 'EMP-103',
    name: 'Priyansh Sharma',
    email: 'priyansh.s@dayflow.hr',
    role: 'EMPLOYEE',
    department: 'Engineering',
    jobTitle: 'Fullstack Engineer',
    joinDate: '2023-06-01',
    phone: '+1 (555) 345-6789',
    address: '42 Wallaby Way, Seattle, WA',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    salary: {
      basic: 4800,
      hra: 1900,
      allowances: 1100,
      deductions: 900,
      netPay: 6900,
    },
  },
  {
    id: 'usr_emp_3',
    employeeId: 'EMP-104',
    name: 'Elena Rostova',
    email: 'elena.rostova@dayflow.hr',
    role: 'EMPLOYEE',
    department: 'Product & Design',
    jobTitle: 'Lead UX Designer',
    joinDate: '2022-11-20',
    phone: '+1 (555) 987-6543',
    address: '350 Fifth Ave, New York, NY',
    photoUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    salary: {
      basic: 5000,
      hra: 2000,
      allowances: 1200,
      deductions: 950,
      netPay: 7250,
    },
  },
  {
    id: 'usr_emp_4',
    employeeId: 'EMP-105',
    name: 'Marcus Vance',
    email: 'marcus.vance@dayflow.hr',
    role: 'EMPLOYEE',
    department: 'Marketing',
    jobTitle: 'Growth Lead',
    joinDate: '2024-01-08',
    phone: '+1 (555) 456-7890',
    address: '100 Market St, Denver, CO',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    salary: {
      basic: 4200,
      hra: 1600,
      allowances: 1000,
      deductions: 800,
      netPay: 6000,
    },
  },
  {
    id: 'usr_emp_5',
    employeeId: 'EMP-106',
    name: 'Aisha Patel',
    email: 'aisha.patel@dayflow.hr',
    role: 'EMPLOYEE',
    department: 'Human Resources',
    jobTitle: 'Talent Acquisition Specialist',
    joinDate: '2023-08-15',
    phone: '+1 (555) 654-3210',
    address: '88 Ocean Drive, Miami, FL',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    salary: {
      basic: 4000,
      hra: 1500,
      allowances: 900,
      deductions: 750,
      netPay: 5650,
    },
  },
  {
    id: 'usr_emp_6',
    employeeId: 'EMP-107',
    name: 'David Kim',
    email: 'david.kim@dayflow.hr',
    role: 'EMPLOYEE',
    department: 'Sales',
    jobTitle: 'Enterprise Account Exec',
    joinDate: '2023-04-12',
    phone: '+1 (555) 789-0123',
    address: '22 Baker St, Chicago, IL',
    photoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    salary: {
      basic: 4500,
      hra: 1800,
      allowances: 2200, // higher commission allowances
      deductions: 1000,
      netPay: 7500,
    },
  },
  {
    id: 'usr_emp_7',
    employeeId: 'EMP-108',
    name: 'Chloe Bennett',
    email: 'chloe.bennett@dayflow.hr',
    role: 'EMPLOYEE',
    department: 'Engineering',
    jobTitle: 'QA Automation Engineer',
    joinDate: '2024-02-01',
    phone: '+1 (555) 210-9876',
    address: '500 Tech Way, San Jose, CA',
    photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    salary: {
      basic: 4400,
      hra: 1700,
      allowances: 1000,
      deductions: 850,
      netPay: 6250,
    },
  },
  {
    id: 'usr_emp_8',
    employeeId: 'EMP-109',
    name: 'James Wilson',
    email: 'james.wilson@dayflow.hr',
    role: 'EMPLOYEE',
    department: 'Customer Support',
    jobTitle: 'Support Team Lead',
    joinDate: '2023-09-01',
    phone: '+1 (555) 321-6549',
    address: '77 Broad St, Boston, MA',
    photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    salary: {
      basic: 3800,
      hra: 1400,
      allowances: 800,
      deductions: 700,
      netPay: 5300,
    },
  },
];

// Helper to generate dates relative to today
const getPastDate = (daysAgo: number): string => {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  return d.toISOString().split('T')[0];
};

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  // Today's attendance
  { id: 'att_t_1', userId: 'usr_emp_1', date: getPastDate(0), checkIn: '08:55:12', status: 'PRESENT', workHours: 8.5 },
  { id: 'att_t_2', userId: 'usr_emp_2', date: getPastDate(0), checkIn: '09:02:44', status: 'PRESENT', workHours: 8.2 },
  { id: 'att_t_3', userId: 'usr_emp_3', date: getPastDate(0), checkIn: '09:45:00', status: 'LATE', workHours: 7.5, notes: 'Traffic delay' },
  { id: 'att_t_4', userId: 'usr_emp_4', date: getPastDate(0), checkIn: '09:10:15', status: 'PRESENT', workHours: 8.1 },
  { id: 'att_t_5', userId: 'usr_emp_5', date: getPastDate(0), checkIn: '08:50:00', status: 'PRESENT', workHours: 8.7 },
  { id: 'att_t_6', userId: 'usr_emp_6', date: getPastDate(0), status: 'LEAVE', notes: 'Approved Medical Leave' },
  { id: 'att_t_7', userId: 'usr_emp_7', date: getPastDate(0), checkIn: '13:00:00', status: 'HALF_DAY', workHours: 4.0, notes: 'Doctor appointment morning' },
  { id: 'att_t_8', userId: 'usr_emp_8', date: getPastDate(0), checkIn: '09:05:30', status: 'PRESENT', workHours: 8.0 },
  { id: 'att_t_9', userId: 'usr_admin_1', date: getPastDate(0), checkIn: '08:30:00', status: 'PRESENT', workHours: 9.0 },

  // Yesterday (1 day ago)
  { id: 'att_y_1', userId: 'usr_emp_1', date: getPastDate(1), checkIn: '09:00:00', checkOut: '17:30:00', status: 'PRESENT', workHours: 8.5 },
  { id: 'att_y_2', userId: 'usr_emp_2', date: getPastDate(1), checkIn: '08:50:00', checkOut: '17:15:00', status: 'PRESENT', workHours: 8.4 },
  { id: 'att_y_3', userId: 'usr_emp_3', date: getPastDate(1), checkIn: '09:05:00', checkOut: '17:40:00', status: 'PRESENT', workHours: 8.6 },
  { id: 'att_y_4', userId: 'usr_emp_4', date: getPastDate(1), status: 'ABSENT', notes: 'Uninformed absence' },
  { id: 'att_y_5', userId: 'usr_emp_5', date: getPastDate(1), checkIn: '09:15:00', checkOut: '17:45:00', status: 'PRESENT', workHours: 8.5 },
  { id: 'att_y_6', userId: 'usr_emp_6', date: getPastDate(1), checkIn: '08:45:00', checkOut: '17:00:00', status: 'PRESENT', workHours: 8.25 },
  { id: 'att_y_7', userId: 'usr_emp_7', date: getPastDate(1), checkIn: '09:00:00', checkOut: '17:30:00', status: 'PRESENT', workHours: 8.5 },
  { id: 'att_y_8', userId: 'usr_emp_8', date: getPastDate(1), checkIn: '08:55:00', checkOut: '17:25:00', status: 'PRESENT', workHours: 8.5 },

  // Past history samples (2-7 days ago)
  ...Array.from({ length: 6 }).flatMap((_, idx) => {
    const daysAgo = idx + 2;
    const dateStr = getPastDate(daysAgo);
    return INITIAL_USERS.map((usr, uIdx) => ({
      id: `att_p_${daysAgo}_${uIdx}`,
      userId: usr.id,
      date: dateStr,
      checkIn: '09:00:00',
      checkOut: '17:30:00',
      status: (uIdx === 3 && daysAgo === 4 ? 'LEAVE' : uIdx === 7 && daysAgo === 3 ? 'HALF_DAY' : 'PRESENT') as AttendanceStatus,
      workHours: uIdx === 7 && daysAgo === 3 ? 4.0 : 8.5,
    }));
  }),
];

export const INITIAL_LEAVES: LeaveRequest[] = [
  {
    id: 'lve_req_101',
    userId: 'usr_emp_1',
    userName: 'Alex Morgan',
    userEmail: 'alex.morgan@dayflow.hr',
    department: 'Engineering',
    type: 'PAID',
    startDate: getPastDate(-3), // 3 days in future
    endDate: getPastDate(-5),   // 5 days in future
    daysCount: 3,
    reason: 'Attending React Next Summit conference and workshops.',
    status: 'PENDING',
    appliedOn: getPastDate(1),
  },
  {
    id: 'lve_req_102',
    userId: 'usr_emp_2',
    userName: 'Priyansh Sharma',
    userEmail: 'priyansh.s@dayflow.hr',
    department: 'Engineering',
    type: 'SICK',
    startDate: getPastDate(0),
    endDate: getPastDate(-1),
    daysCount: 2,
    reason: 'Dental surgery recovery prescribed by doctor.',
    status: 'PENDING',
    appliedOn: getPastDate(0),
  },
  {
    id: 'lve_req_103',
    userId: 'usr_emp_3',
    userName: 'Elena Rostova',
    userEmail: 'elena.rostova@dayflow.hr',
    department: 'Product & Design',
    type: 'PAID',
    startDate: getPastDate(-10),
    endDate: getPastDate(-14),
    daysCount: 5,
    reason: 'Annual family vacation leave.',
    status: 'APPROVED',
    appliedOn: getPastDate(18),
    adminComment: 'Enjoy your trip! Project lead backup confirmed.',
    reviewedBy: 'Sarah Jenkins',
    reviewedAt: getPastDate(16),
  },
  {
    id: 'lve_req_104',
    userId: 'usr_emp_4',
    userName: 'Marcus Vance',
    userEmail: 'marcus.vance@dayflow.hr',
    department: 'Marketing',
    type: 'UNPAID',
    startDate: getPastDate(5),
    endDate: getPastDate(6),
    daysCount: 2,
    reason: 'Personal urgent real estate relocation matters.',
    status: 'REJECTED',
    appliedOn: getPastDate(7),
    adminComment: 'Key launch date conflict. Please reschedule for the following week.',
    reviewedBy: 'Sarah Jenkins',
    reviewedAt: getPastDate(6),
  },
  {
    id: 'lve_req_105',
    userId: 'usr_emp_6',
    userName: 'David Kim',
    userEmail: 'david.kim@dayflow.hr',
    department: 'Sales',
    type: 'SICK',
    startDate: getPastDate(0),
    endDate: getPastDate(0),
    daysCount: 1,
    reason: 'Fever and viral flu rest.',
    status: 'APPROVED',
    appliedOn: getPastDate(1),
    adminComment: 'Get well soon!',
    reviewedBy: 'Sarah Jenkins',
    reviewedAt: getPastDate(0),
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_1',
    userId: 'usr_emp_1',
    title: 'Leave Request Received',
    message: 'Your Paid Leave request (3 days) is pending HR review.',
    timestamp: getPastDate(1),
    read: true,
    type: 'LEAVE_APPROVAL',
  },
  {
    id: 'notif_2',
    userId: 'usr_admin_1',
    title: 'New Leave Request',
    message: 'Priyansh Sharma applied for Sick Leave (2 days).',
    timestamp: getPastDate(0),
    read: false,
    type: 'LEAVE_APPROVAL',
  },
  {
    id: 'notif_3',
    userId: 'usr_emp_3',
    title: 'Leave Approved',
    message: 'Your 5-day Paid Leave was approved by Sarah Jenkins.',
    timestamp: getPastDate(16),
    read: true,
    type: 'LEAVE_APPROVAL',
  },
];
